admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_evenement:
    path:     /gestion_evenement
    defaults: { _controller: AdminBundle:Dashboard:afficherEvenementAdmin }

admin_evenement_semaine:
    path:     /gestion_evenement_semaine
    defaults: { _controller: AdminBundle:Dashboard:findWeek }

admin_supprimer_evenement:
    path:     /gestion_evenement_supp
    defaults: { _controller: AdminBundle:Dashboard:supprimerEvenementAdmin }