<?php

namespace ProduitBundle\Repository;

/**
 * LikeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
